// Generated by GraphWalker (http://www.graphwalker.org)
package com.mbt;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "com/mbt/MusicPlayer.graphml")
public interface MusicPlayerModel {

    @Vertex()
    void v_FileReady();

    @Vertex()
    void v_FilePlaying();

    @Vertex()
    void v_FilePaused();

    @Edge()
    void e_Open();

    @Edge()
    void e_Start();

    @Edge()
    void e_Stop();

    @Edge()
    void e_Pause();

    @Edge()
    void e_Resume();

}
